import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../lib/api'
import Spinner from '../components/Spinner'

export default function CourseBuilder() {
  const { courseId } = useParams(); const [course, setCourse] = useState(null); const [sectionName, setSectionName] = useState(''); const [lesson, setLesson] = useState({ sectionId: '', title: '', description: '' }); const [video, setVideo] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const reload = () => api.course.details(courseId).then(res => setCourse(Array.isArray(res.data) ? res.data[0] : res.data))
  useEffect(() => { reload().catch(err => setError(err.message)) }, [courseId])
  async function addSection(e) { e.preventDefault(); setBusy(true); setError(''); try { await api.course.addSection({ sectionName, courseId }); setSectionName(''); setMessage('Section added.'); await reload() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  async function addLesson(e) { e.preventDefault(); if (!video) return setError('Choose a video file.'); setBusy(true); setError(''); try { const fd = new FormData(); fd.append('sectionId', lesson.sectionId); fd.append('title', lesson.title); fd.append('description', lesson.description); fd.append('video', video); await api.course.addSubSection(fd); setLesson({ sectionId: '', title: '', description: '' }); setVideo(null); setMessage('Lesson added.'); await reload() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  if (!course && !error) return <Spinner />
  return <div className="dashboard-page"><div className="page-heading compact"><span className="eyebrow">Course builder</span><h1>{course?.courseName || 'Build course'}</h1><p className="muted">Add sections first, then upload lessons into a section.</p></div>{message && <div className="alert success">{message}</div>}{error && <div className="alert error">{error}</div>}<div className="builder-grid"><form className="panel content-block stack-form" onSubmit={addSection}><h2>Add section</h2><label>Section name<input value={sectionName} onChange={e => setSectionName(e.target.value)} required placeholder="Getting started" /></label><button className="btn btn-primary" disabled={busy}>Add section</button></form><form className="panel content-block stack-form" onSubmit={addLesson}><h2>Add video lesson</h2><label>Section<select value={lesson.sectionId} onChange={e => setLesson({ ...lesson, sectionId: e.target.value })} required><option value="">Choose section</option>{course?.courseContent?.map(s => <option value={s._id} key={s._id}>{s.sectionName}</option>)}</select></label><label>Lesson title<input value={lesson.title} onChange={e => setLesson({ ...lesson, title: e.target.value })} required /></label><label>Description<textarea value={lesson.description} onChange={e => setLesson({ ...lesson, description: e.target.value })} required /></label><label>Video<input type="file" accept="video/*" onChange={e => setVideo(e.target.files?.[0])} required /></label><button className="btn btn-primary" disabled={busy}>Upload lesson</button></form></div><div className="panel content-block"><div className="section-head small"><h2>Current content</h2><Link to={`/courses/${courseId}`}>View public page →</Link></div>{course?.courseContent?.length ? course.courseContent.map(s => <div className="builder-section" key={s._id}><strong>{s.sectionName}</strong><span>{s.subSection?.length || 0} lessons</span>{s.subSection?.map(l => <div className="builder-lesson" key={l._id}>{l.title}</div>)}</div>) : <p className="muted">No sections yet.</p>}</div></div>
}
