import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../lib/api'

const initial = { courseName: '', courseDescription: '', whatYouWillLearn: '', price: '', tag: '', category: '', status: 'Draft', instructions: '' }
export default function CreateCourse() {
  const [form, setForm] = useState(initial); const [thumbnail, setThumbnail] = useState(null); const [categories, setCategories] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate()
  useEffect(() => { api.course.categories().then(res => setCategories(res.data || [])).catch(err => setError(err.message)) }, [])
  const update = e => setForm({ ...form, [e.target.name]: e.target.value })
  async function submit(e) { e.preventDefault(); if (!thumbnail) return setError('Choose a thumbnail image.'); setBusy(true); setError(''); try { const body = new FormData(); Object.entries(form).forEach(([k,v]) => body.append(k, v)); body.append('thumbnailImage', thumbnail); const res = await api.course.create(body); navigate(`/dashboard/course-builder/${res.data._id}`, { state: { course: res.data } }) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <div className="dashboard-page"><div className="page-heading compact"><span className="eyebrow">Instructor</span><h1>Create a course</h1><p className="muted">Create the course first, then add sections and video lessons.</p></div>{error && <div className="alert error">{error}</div>}<form className="panel content-block stack-form" onSubmit={submit}><label>Course name<input name="courseName" value={form.courseName} onChange={update} required /></label><label>Description<textarea name="courseDescription" value={form.courseDescription} onChange={update} required /></label><label>What will students learn?<textarea name="whatYouWillLearn" value={form.whatYouWillLearn} onChange={update} required /></label><div className="form-grid two"><label>Price (₹)<input type="number" min="0" name="price" value={form.price} onChange={update} required /></label><label>Category<select name="category" value={form.category} onChange={update} required><option value="">Choose category</option>{categories.map(c => <option value={c._id} key={c._id}>{c.name}</option>)}</select></label></div><div className="form-grid two"><label>Tags<input name="tag" value={form.tag} onChange={update} placeholder="JavaScript, Web Development" required /></label><label>Status<select name="status" value={form.status} onChange={update}><option>Draft</option><option>Published</option></select></label></div><label>Requirements / instructions<textarea name="instructions" value={form.instructions} onChange={update} placeholder="Basic JavaScript knowledge" /></label><label>Thumbnail<input type="file" accept="image/*" onChange={e => setThumbnail(e.target.files?.[0])} required /></label><button className="btn btn-primary" disabled={busy}>{busy ? 'Creating...' : 'Create course & add content'}</button></form></div>
}
